services:
  treino:
    build: ./treino
    volumes:
      - ./dados:/dados:ro
      - ./modelo:/modelo

  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./modelo:/modelo:ro
    depends_on:
      treino:
        condition: service_completed_successfully
